language: android
jdk: oraclejdk7
sudo: false

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

script: ./gradlew testRelease
